"""Write Boswell output files to <repo>/.boswell/."""

import json
from datetime import datetime
from pathlib import Path

BANNER = "<!-- Generated by Boswell — https://github.com/eddiebm/boswell -->\n\n"


def write_repo_output(
    repo_path: Path,
    results: dict[str, str],
    scan,
    cost_usd: float,
) -> Path:
    """Write all four docs + metadata.json. Returns the .boswell/ directory."""
    out_dir = repo_path / ".boswell"
    out_dir.mkdir(exist_ok=True)

    run_date = datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"*Boswell audit — {scan.name} — {run_date}*\n\n"

    (out_dir / "audit.md").write_text(BANNER + header + results["audit"], encoding="utf-8")
    (out_dir / "handoff.md").write_text(BANNER + header + results["handoff"], encoding="utf-8")
    (out_dir / "audit-simple.md").write_text(BANNER + header + results["audit_simple"], encoding="utf-8")
    (out_dir / "handoff-simple.md").write_text(BANNER + header + results["handoff_simple"], encoding="utf-8")
    if results.get("lessons"):
        (out_dir / "lessons.md").write_text(BANNER + header + results["lessons"], encoding="utf-8")

    leak_findings = results.get("leak_findings", [])
    metadata = {
        "repo": scan.name,
        "run_at": run_date,
        "stack": scan.stack,
        "env_vars_found": scan.env_var_keys,
        "secret_warnings_count": len(results.get("secret_warnings", [])),
        "leak_findings": leak_findings,
        "files_scanned": len(scan.all_files),
        "cost_usd": round(cost_usd, 4),
    }
    (out_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    # Best-effort: sync run_at, stack, and platforms to Neon so both instances see the scan.
    try:
        import os as _os
        from . import db as _db
        db_url = _db.get_url()
        if db_url:
            _db.upsert_repo_meta(
                db_url,
                repo_name=scan.name,
                run_at=run_date,
                stack=list(scan.stack),
            )
    except Exception:
        pass

    return out_dir


def write_portfolio(batch_root: Path, all_results: list[dict]) -> Path:
    """Write PORTFOLIO.md summarizing all repos in a batch run."""
    out_dir = batch_root / ".boswell"
    out_dir.mkdir(exist_ok=True)

    run_date = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Portfolio Overview\n",
        f"*Boswell batch run — {run_date}*\n\n",
        "| Repo | Stack | Deploy Verdict | Top Security Risk | Fate | Cost |\n",
        "|------|-------|----------------|-------------------|------|------|\n",
    ]

    total_cost = 0.0
    for r in all_results:
        if r.get("error"):
            lines.append(f"| {r['name']} | — | ERROR: {r['error']} | — | — | — |\n")
            continue
        stack = ", ".join(r.get("stack", [])[:3]) or "unknown"
        verdict = r.get("deploy_verdict", "—")
        top_risk = r.get("top_risk", "—")
        fate = r.get("fate", "—")
        cost = r.get("cost_usd", 0)
        total_cost += cost
        lines.append(f"| {r['name']} | {stack} | {verdict} | {top_risk} | {fate} | ${cost:.3f} |\n")

    lines.append(f"\n**Total cost:** ${total_cost:.3f}\n")
    lines.append(f"\n**Repos processed:** {len(all_results)}\n")

    portfolio_path = out_dir / "PORTFOLIO.md"
    portfolio_path.write_text("".join(lines), encoding="utf-8")
    return portfolio_path


def extract_verdict(audit_text: str) -> str:
    """Pull the deploy verdict line from audit.md for the portfolio table."""
    for line in audit_text.splitlines():
        low = line.lower()
        if "could deploy tomorrow" in low:
            return "Could deploy tomorrow"
        if "do not deploy" in low or "don't deploy" in low:
            return "Do not deploy"
        if "needs" in low and "fix" in low and "verdict" in low:
            return line.replace("**Verdict:**", "").strip()[:60]
    return "—"


def extract_top_risk(audit_text: str) -> str:
    """Pull the first CRITICAL or HIGH finding for the portfolio table."""
    for line in audit_text.splitlines():
        if "[CRITICAL]" in line or "[HIGH]" in line:
            return line.strip().lstrip("- ")[:80]
    return "None found"


def extract_fate(handoff_text: str) -> str:
    """Pull the Recommended fate line from handoff.md."""
    for line in handoff_text.splitlines():
        if "**Recommended fate:**" in line:
            return line.replace("**Recommended fate:**", "").strip()[:60]
    return "—"
